<% gh_run_id = ENV['RUN_ID'] || 'local' %>
default: --format pretty --format html --out=html-report/html-report.html
gh-headless-firefox: DRIVER=headless_firefox --format pretty --format junit --out=reports/junit-<%= gh_run_id %>.xml --publish-quiet
