<% gh_run_id = ENV['RUN_ID'] %>
default: --format pretty --format html --out=test_results.html
gh-headless-firefox: DRIVER=headless_firefox --format pretty --format junit --out=reports/junit-<%= gh_run_id %>.xml --publish-quiet
